version: "3.8"

services:
  app:
    build: .
    env_file:
      - ./.env
    working_dir: "/backend"
    command: >
      /bin/sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - ./:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: redis-server --requirepass uwords_redis_password
    restart: always
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: worker
    command: celery -A uwords_api.celery_app worker --loglevel=INFO
    env_file:
      - ./.env
    environment:
      - C_FORCE_ROOT=1
    depends_on:
      - db
      - redis

  scheduler:
    build: .
    container_name: scheduler
    command: celery -A uwords_api.celery_app beat --loglevel=INFO
    env_file:
      - ./.env
    environment:
      - C_FORCE_ROOT=1
    restart: always
    depends_on:
      - db
      - redis
    