# Generated by Django 5.0.4 on 2024-04-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='value',
            field=models.CharField(unique=True, verbose_name='Слово'),
        ),
    ]
