# Generated by Django 5.0.4 on 2024-04-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words_api', '0004_rename_audio_word_audiolink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='audioLink',
            field=models.CharField(null=True, verbose_name='Аудиозапись'),
        ),
    ]
