# Generated by Django 5.0.4 on 2024-04-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words_api', '0005_alter_word_audiolink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userword',
            options={'verbose_name': 'Слово (пользователя)', 'verbose_name_plural': 'Слова (пользователя)'},
        ),
    ]
