# Generated by Django 5.0.4 on 2024-04-10 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_api', '0001_initial'),
        ('words_api', '0006_alter_userword_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='category_api.category', verbose_name='Категория'),
        ),
    ]
